### ISSUE TITLE
Database Schema Presentation

### ISSUE THREAD

**Issue by Sammydepoj** [zuri-training/Project-price-compare-team-25#16]

**Comment by mzAnnie** [comment]
good

**Comment by Est200** [comment]
Hello, viewers. I'm one of the database schema workforce. I am my fellow team mates worked
on the schema and the presentation. 
The database schema was designed according to the instructions we were given. 
We mapped out all the important entities and the features they should have.

**Comment by Sammydepoj** [comment]
Completed
