### ISSUE TITLE
homepage page design 

### ISSUE THREAD

**Issue by mzAnnie** [zuri-training/Project-price-compare-team-25#40]

**Comment by PromiseUdia** [comment]
Web Design for the Homepage is completed
[https://www.figma.com/file/J4mwn9yjSAErf2s8OYLRXb/Team25_Price_Comp_Project?node-id=90%3A248](url)

**Comment by PromiseUdia** [comment]
mobile Screen designed and moved to developers for implementations
[https://www.figma.com/file/J4mwn9yjSAErf2s8OYLRXb/Team25_Price_Comp_Project?node-id=90%3A248](url)
